### PR TITLE
Add `PlainMatrix` and `SecureMatrix`

### PR DESCRIPTION
**Pull request by ArseniyKholod**
I was wondering about 2D simulations and thought, that it should not be so difficult to add `PlainMatrix` and `SecureMatrix` based on currently existing `PlainVector` and `SecureVector`, this is my try.
I pinned `OpenFHE_jll` to v1.1.2 to let tests run.

### CODE REVIEW

**Comment by ArseniyKholod** [comment]
Unfortunately, the concept used in the previous commits is not useful, because of the extremely bad efficiency. I tried to build a secure matrix simply combining many secure vectors as rows of the matrix, but e.g. for 40*40 Matrix it's necessary to use 40 `SecureVector`. 40*40 matrix could be fit in a single `SecureVector` with dimensional of the ring more than 3200. In case of using 40 such vectors to hold a single matrix, that could fit in a single all computations become 40 times slower. The solution could be to decrease a ring dimension for these vectors used in a matrix, but due to the security reason it's almost impossible. So as a next step I will try to find a way to fit a matrix in a single vector, simply fusing all rows together and define all necessary arithmetical operations on it.

**Comment by sloede** [comment]
> Unfortunately, the concept used in the previous commits is not useful, because of the extremely bad efficiency. I tried to build a secure matrix simply combining many secure vectors as rows of the matrix, but e.g. for 40 * 40 Matrix it's necessary to use 40 `SecureVector`. 40 * 40 matrix could be fit in a single `SecureVector` with dimension of the ring more than 3200. In case of using 40 such vectors to hold a single matrix, that could fit in a single, all computations become 40 times slower. The solution could be to decrease a ring dimension for these vectors used in a matrix, but due to the security reason it's almost impossible. So as a next step I will try to find a way to fit a matrix in a single vector, simply fusing all rows together and define all necessary arithmetical operations on it.

Thanks, very interesting findings. Please make sure that you record your measurements such that we can use them in a publication or talk.

**Comment by sloede** [comment]
It might be worthwhile to search the Discourse for terms related to matrix: https://openfhe.discourse.group/search?q=matrix

The first few results seem interesting, but also indicate that it might be a non-trivial goal to achieve (at least if trying to do it efficiently).

**Comment by ArseniyKholod** [comment]
> It might be worthwhile to search the Discourse for terms related to matrix: https://openfhe.discourse.group/search?q=matrix
> 
> The first few results seem interesting, but also indicate that it might be a non-trivial goal to achieve (at least if trying to do it efficiently).

Thanks for the idea! I will record all results!

**Comment by sloede** [comment]
Is this still relevant? I lost track whether this is already implemented in SA.jl or not...

**Pull request closed without merging**
